export const routes = {
    login: "/login",
    register: "/register",
    searchProduct: "/admin/product",
    searchAccount: "/admin/account",
    searchCategory: "/admin/category",
    searchSupplier: "/admin/supplier",
    createProduct: "/admin/create_product",
    home: "/",
    account: "/account",
    profile: "/account/profile",
    address: '/account/address',
    password: "/account/password",
    cart: "/cart",
    product: "/product",
    productDetail: "/product/:id",
    products: "/products",
    search: "/search",
    importGoods: "/admin/goods",
    goodsReceipt: "/goods/receipt",
    order: "/order",
    warehouse: "/admin/warehouse",
    staff: "/admin/staff",
    staffAccountConfirmPassword: "/staff_account_confirm_email",
    stockDetail: "/admin/stock_detail"
};